version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
references:
  yarn_cache_key: &yarn_cache_key yarn-v1-{{ checksum "yarn.lock" }}
jobs:
  build:
    docker:
      - image: circleci/node:10.13
    steps:
      - checkout
      - restore_cache:
          keys:
            - *yarn_cache_key
            - yarn-v1-
      - run:
          name: dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: build
          command: yarn build
      - run:
          name: test
          command: yarn test:prod
      - codecov/upload:
          file: coverage/*.json
          flags: backend
      - run:
          name: deploy
          command: yarn run semantic-release || true
      - save_cache:
          key: *yarn_cache_key
          paths: ~/circleci/node_modules
